<?php

return array (
  'SITE_URL' => 'http://scp.weilearn.com',
  'DB_CONFIG' => 'mysql://scp:liux2013Bx@localhost:3306/scp',
  'DB_PREFIX' => 'ecm_',
  'LANG' => 'sc-utf-8',
  'COOKIE_DOMAIN' => '',
  'COOKIE_PATH' => '/',
  'ECM_KEY' => '0c3c7da0f90a9b4566d6bda40dbacc72',
  'MALL_SITE_ID' => 'EMNI0LHR19WHATTG',
  'ENABLED_GZIP' => 0,
  'DEBUG_MODE' => 0,
  'CACHE_SERVER' => 'default',
  'MEMBER_TYPE' => 'uc',
  'ENABLED_SUBDOMAIN' => 0,
  'SUBDOMAIN_SUFFIX' => '',
  'SESSION_TYPE' => 'mysql',
  'SESSION_MEMCACHED' => 'localhost:11211',
  'CACHE_MEMCACHED' => 'localhost:11211',
  'UC_DBCHARSET' => 'utf8',
  'UC_DBTABLEPRE' => '`scp`.bbs_ucenter_',
  'UC_KEY' => 'l5Pf89teA8QdV7x9N905g4a95e7ao8Y42du917Hak292D8B9f8w6W2fdO6t501t3',
  'UC_APPID' => '3',
  'UC_DBHOST' => 'localhost',
  'UC_DBNAME' => 'scp',
  'UC_DBUSER' => 'scp',
  'UC_DBPW' => 'liux2013Bx',
  'UC_CHARSET' => 'utf-8',
  'UC_API' => 'http://scp.weilearn.com/bbs/uc_server/',
  'UC_PATH' => 'uc_client',
  'UC_CONNECT' => 'mysql',
  'UC_IP' => '42.121.121.9',
  'UC_DBCONNECT' => '0',
  'DZ_DB' => 'scp',
  'DZ_PRE' => 'bbs_',
);

?>